spring:
  application:
    name: rag-chatbot
  config:
    import: optional:file:application-secret.yml

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

qdrant:
  base-url: http://localhost:6333
  collection-name: your_collection